//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photography.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public int EmployeeId { get; set; }
        public string EmplyeeUniqueID__UniqueId__UniqueId__UniqueID_______ { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserType { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public byte[] City { get; set; }
        public byte[] State { get; set; }
        public byte[] CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public byte[] ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DailyWages { get; set; }
        public Nullable<int> HalfDayWages { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
